/*
Copyright (C) 2010-2013  Le Hoang Quyen (lehoangq@gmail.com)

This program is free software; you can redistribute it and/or
modify it under the terms of the MIT license.  See the file
COPYING.txt included with this distribution for more information.


*/

#include "../HQPlatformDef.h"
#include "../HQEngineCustomHeap.h"
#include "HQReturnValDebugString.h"
#include "stdlib.h"

#if defined DEBUG || defined _DEBUG

#define DECL_HQ_RETURN_VAL_DBG_STRING(val) const char _##val##String[] = #val
#define RETURN_VAL_SWITCH_CASE(val) case val : return _##val##String

DECL_HQ_RETURN_VAL_DBG_STRING( HQ_OK );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_LOAD_LIBRARY );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_CREATE_DEVICE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_INIT_DEVICE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_DEVICE_ALREADY_EXISTS );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_DEVICE_NOT_INIT );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_MEM_ALLOC );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_RENDER_ALREADY_BEGUN );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_RENDER_NOT_BEGUN  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_WARNING_VIEWPORT_IS_INVALID  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_INVALID_ID  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_WRONG_SHADER_TYPE  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_SHADER_PARAMETER_NOT_FOUND  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_SHADER_PROGRAM_NEED_SHADEROBJECT  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_NOT_IN_TEXT_MODE  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_CANT_RENDER_IN_TEXT_MODE  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_IN_TEXT_MODE_CANT_CHANGE_VIEW_STAGE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_DEVICE_LOST  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_SHADER_SOURCE_IS_NOT_SUPPORTED );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_TEXTURE_NOT_2D  );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_TEXTURE_NOT_CUBE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_NOT_ENOUGH_CUBE_FACES );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_RENDERTARGET_AND_DEPTHSTENCIL_NOT_COMPATIBLE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_RENDERTARGET_IS_ACTIVE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_DEPTHSTENCILBUFFER_IS_ACTIVE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_FORMAT_NOT_SUPPORT );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_MULTISAMPLE_TYPE_NOT_SUPPORT );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_TOO_MANY_ATTRIBUTES );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_INVALID_SIZE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_FAILED_NOT_DYNAMIC_RESOURCE );
DECL_HQ_RETURN_VAL_DBG_STRING( HQ_RETURN_FORCE_DWORD  );

const char* HQReturnValToString(HQReturnVal val)
{
	switch(val)
	{
		RETURN_VAL_SWITCH_CASE( HQ_OK );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_LOAD_LIBRARY );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_CREATE_DEVICE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_INIT_DEVICE );
		RETURN_VAL_SWITCH_CASE( HQ_DEVICE_ALREADY_EXISTS );
		RETURN_VAL_SWITCH_CASE( HQ_DEVICE_NOT_INIT );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_MEM_ALLOC );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_RENDER_ALREADY_BEGUN );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_RENDER_NOT_BEGUN  );
		RETURN_VAL_SWITCH_CASE( HQ_WARNING_VIEWPORT_IS_INVALID  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_INVALID_ID  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_WRONG_SHADER_TYPE  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_SHADER_PARAMETER_NOT_FOUND  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_SHADER_PROGRAM_NEED_SHADEROBJECT  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_NOT_IN_TEXT_MODE  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_CANT_RENDER_IN_TEXT_MODE  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_IN_TEXT_MODE_CANT_CHANGE_VIEW_STAGE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_DEVICE_LOST  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_SHADER_SOURCE_IS_NOT_SUPPORTED );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_TEXTURE_NOT_2D  );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_TEXTURE_NOT_CUBE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_NOT_ENOUGH_CUBE_FACES );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_RENDERTARGET_AND_DEPTHSTENCIL_NOT_COMPATIBLE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_RENDERTARGET_IS_ACTIVE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_DEPTHSTENCILBUFFER_IS_ACTIVE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_FORMAT_NOT_SUPPORT );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_MULTISAMPLE_TYPE_NOT_SUPPORT );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_TOO_MANY_ATTRIBUTES );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_INVALID_SIZE );
		RETURN_VAL_SWITCH_CASE( HQ_FAILED_NOT_DYNAMIC_RESOURCE );
		RETURN_VAL_SWITCH_CASE( HQ_RETURN_FORCE_DWORD  );
	}
	return NULL;
};

#else

const char* HQReturnValToString(HQReturnVal val)
{
	return NULL;
}

#endif
