echo "armabi:"
echo "Compile++ arm    : HQUtilMath <= HQMatrix3x4.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++  -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv5te  -mtune=xscale  -msoft-float -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi/include -Ijni/../../../Source/HQUtilMath  -DANDROID -DCMATH=1 -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQMatrix3x4.cpp -o ./obj/local/armeabi/objs/HQUtilMath/HQMatrix3x4.s  && ( if [ -f "./obj/local/armeabi/objs/HQUtilMath/HQMatrix3x4.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi/objs/HQUtilMath/HQMatrix3x4.o.d.org > ./obj/local/armeabi/objs/HQUtilMath/HQMatrix3x4.o.d &&  rm -f ./obj/local/armeabi/objs/HQUtilMath/HQMatrix3x4.o.d.org;  fi )
echo "Compile++ arm    : HQUtilMath <= HQMatrix4.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++  -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv5te  -mtune=xscale  -msoft-float -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi/include -Ijni/../../../Source/HQUtilMath  -DANDROID -DCMATH=1 -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQMatrix4.cpp -o ./obj/local/armeabi/objs/HQUtilMath/HQMatrix4.s  && ( if [ -f "./obj/local/armeabi/objs/HQUtilMath/HQMatrix4.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi/objs/HQUtilMath/HQMatrix4.o.d.org > ./obj/local/armeabi/objs/HQUtilMath/HQMatrix4.o.d &&  rm -f ./obj/local/armeabi/objs/HQUtilMath/HQMatrix4.o.d.org;  fi )
echo "Compile++ arm    : HQUtilMath <= HQQuaternion.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++ -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv5te  -mtune=xscale  -msoft-float -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi/include -Ijni/../../../Source/HQUtilMath  -DANDROID -DCMATH=1 -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQQuaternion.cpp -o ./obj/local/armeabi/objs/HQUtilMath/HQQuaternion.s  && ( if [ -f "./obj/local/armeabi/objs/HQUtilMath/HQQuaternion.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi/objs/HQUtilMath/HQQuaternion.o.d.org > ./obj/local/armeabi/objs/HQUtilMath/HQQuaternion.o.d &&  rm -f ./obj/local/armeabi/objs/HQUtilMath/HQQuaternion.o.d.org;  fi )
echo "Compile++ arm    : HQUtilMath <= HQVector.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++ -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv5te  -mtune=xscale  -msoft-float -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi/include -Ijni/../../../Source/HQUtilMath  -DANDROID -DCMATH=1 -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQVector.cpp -o ./obj/local/armeabi/objs/HQUtilMath/HQVector.s  && ( if [ -f "./obj/local/armeabi/objs/HQUtilMath/HQVector.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi/objs/HQUtilMath/HQVector.o.d.org > ./obj/local/armeabi/objs/HQUtilMath/HQVector.o.d &&  rm -f ./obj/local/armeabi/objs/HQUtilMath/HQVector.o.d.org;  fi )

echo "armabi-v7a:"
echo "Compile++ arm    : HQUtilMath <= HQMatrix3x4.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++ -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv7-a  -mfloat-abi=softfp  -mfpu=vfp -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300 -mfpu=neon  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include -Ijni/../../../Source/HQUtilMath  -DANDROID  -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQMatrix3x4.cpp -o ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix3x4.s  && ( if [ -f "./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix3x4.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix3x4.o.d.org > ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix3x4.o.d &&  rm -f ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix3x4.o.d.org;  fi )
echo "Compile++ arm    : HQUtilMath <= HQMatrix4.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++ -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv7-a  -mfloat-abi=softfp  -mfpu=vfp -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300 -mfpu=neon  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include -Ijni/../../../Source/HQUtilMath  -DANDROID  -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQMatrix4.cpp -o ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix4.s  && ( if [ -f "./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix4.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix4.o.d.org > ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix4.o.d &&  rm -f ./obj/local/armeabi-v7a/objs/HQUtilMath/HQMatrix4.o.d.org;  fi )
echo "Compile++ arm    : HQUtilMath <= HQQuaternion.cpp"
"$(cygpath --unix "$NDK_DIR")"/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++ -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv7-a  -mfloat-abi=softfp  -mfpu=vfp -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300 -mfpu=neon  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include -Ijni/../../../Source/HQUtilMath  -DANDROID  -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQQuaternion.cpp -o ./obj/local/armeabi-v7a/objs/HQUtilMath/HQQuaternion.s  && ( if [ -f "./obj/local/armeabi-v7a/objs/HQUtilMath/HQQuaternion.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi-v7a/objs/HQUtilMath/HQQuaternion.o.d.org > ./obj/local/armeabi-v7a/objs/HQUtilMath/HQQuaternion.o.d &&  rm -f ./obj/local/armeabi-v7a/objs/HQUtilMath/HQQuaternion.o.d.org;  fi )
echo "Compile++ arm    : HQUtilMath <= HQVector.cpp"
/cygdrive/h/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-g++  -fpic  -ffunction-sections  -funwind-tables  -fstack-protector  -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__  -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__   -Wno-psabi -march=armv7-a  -mfloat-abi=softfp  -mfpu=vfp -fno-exceptions -fno-rtti  -O2  -fomit-frame-pointer  -fstrict-aliasing     -funswitch-loops      -finline-limit=300 -mfpu=neon  -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/include -IH:/android-ndk-r7/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include -Ijni/../../../Source/HQUtilMath  -DANDROID  -Wa,--noexecstack  -fexceptions -frtti -fexceptions    -O2 -DNDEBUG -g      -IH:/android-ndk-r7/platforms/android-3/arch-arm/usr/include  -S   jni/../../../Source/HQUtilMath/HQVector.cpp -o ./obj/local/armeabi-v7a/objs/HQUtilMath/HQVector.s  && ( if [ -f "./obj/local/armeabi-v7a/objs/HQUtilMath/HQVector.o.d.org" ]; then  awk -f /cygdrive/h/android-ndk-r7/build/awk/convert-deps-to-cygwin.awk ./obj/local/armeabi-v7a/objs/HQUtilMath/HQVector.o.d.org > ./obj/local/armeabi-v7a/objs/HQUtilMath/HQVector.o.d &&  rm -f ./obj/local/armeabi-v7a/objs/HQUtilMath/HQVector.o.d.org;  fi )

