cd ..
cd ..
cd Source
cd HQUtilMath
touch HQAABB.cpp
touch HQBSP.cpp 
touch HQMatrix3x4.cpp 
touch HQMatrix4.cpp 
touch HQOBB.cpp 
touch HQPlane.cpp 
touch HQPolygon.cpp 
touch HQPrimeNumber.cpp 
touch HQQuaternion.cpp 
touch HQRay.cpp 
touch HQSphere.cpp 
touch HQVector.cpp
cd ..
cd ..
cd Android-ndk
cd HQEngineUtilMath