/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef __APPLE__
#include <JavaVM/jni.h>
#else
#include <jni.h>
#endif
/* Header for class hqengineshadercompiler_HQEngineShaderCompilerView */

#ifndef _Included_hqengineshadercompiler_HQEngineShaderCompilerView
#define _Included_hqengineshadercompiler_HQEngineShaderCompilerView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hqengineshadercompiler_HQEngineShaderCompilerView
 * Method:    InitGL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hqengineshadercompiler_HQEngineShaderCompilerView_InitGL
  (JNIEnv *, jobject);

/*
 * Class:     hqengineshadercompiler_HQEngineShaderCompilerView
 * Method:    ReleaseGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hqengineshadercompiler_HQEngineShaderCompilerView_ReleaseGL
  (JNIEnv *, jobject);

/*
 * Class:     hqengineshadercompiler_HQEngineShaderCompilerView
 * Method:    CompileGLSL
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hqengineshadercompiler_HQEngineShaderCompilerView_CompileGLSL
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
