/*
Copyright (C) 2010-2013  Le Hoang Quyen (lehoangq@gmail.com)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the
License, or (at your option) any later version.  See the file
COPYING.txt included with this distribution for more information.


*/

#ifndef _HQ_RETURN_VAL_
#define _HQ_RETURN_VAL_

/*-------------return value--------------*/
typedef enum HQReturnVal
{
	HQ_OK  = 1,
	HQ_FAILED = 0,
	HQ_FAILED_LOAD_LIBRARY = 0x1fffffff,
	HQ_FAILED_CREATE_DEVICE = 2,
	HQ_FAILED_INIT_DEVICE = 0x2fffffff,
	HQ_DEVICE_ALREADY_EXISTS = 3,
	HQ_DEVICE_NOT_INIT = 4,
	HQ_DEVICE_LOST = 0x3fffffff,
	HQ_FAILED_MEM_ALLOC = 5,
	HQ_FAILED_RENDER_ALREADY_BEGUN = 6,
	HQ_FAILED_RENDER_NOT_BEGUN = 7,
	HQ_WARNING_VIEWPORT_IS_INVALID = 8,
	HQ_FAILED_INVALID_ID = 0x4fffffff,
	HQ_FAILED_WRONG_SHADER_TYPE = 12,
	HQ_FAILED_SHADER_PARAMETER_NOT_FOUND = 13,
	HQ_FAILED_SHADER_PROGRAM_NEED_SHADEROBJECT = 14,
	HQ_FAILED_NOT_IN_TEXT_MODE  = 15,
	HQ_FAILED_CANT_RENDER_IN_TEXT_MODE = 16,
	HQ_FAILED_IN_TEXT_MODE_CANT_CHANGE_VIEW_STAGE = 17,
	HQ_FAILED_DEVICE_LOST = 18,
	HQ_FAILED_SHADER_SOURCE_IS_NOT_SUPPORTED = 19,
	HQ_FAILED_TEXTURE_NOT_2D = 20,
	HQ_FAILED_TEXTURE_NOT_CUBE = 21,
	HQ_FAILED_NOT_ENOUGH_CUBE_FACES = 22,
	HQ_FAILED_RENDERTARGET_AND_DEPTHSTENCIL_NOT_COMPATIBLE = 23,
	HQ_FAILED_RENDERTARGET_IS_ACTIVE = 24,
	HQ_FAILED_DEPTHSTENCILBUFFER_IS_ACTIVE = 25,
	HQ_FAILED_FORMAT_NOT_SUPPORT = 26 ,
	HQ_FAILED_MULTISAMPLE_TYPE_NOT_SUPPORT = 27 ,
	HQ_FAILED_TOO_MANY_ATTRIBUTES = 28,
	HQ_FAILED_INVALID_SIZE = 29,
	HQ_FAILED_NOT_DYNAMIC_RESOURCE = 30,
	HQ_FAILED_PLAYING = 31,
	HQ_FAILED_INVALID_PARAMETER = 32,
	HQ_FAILED_AUDIO_SOURCE_BUFFER_MISMATCH = 33,
	HQ_WARNING_AUDIO_SOURCE_BUFFER_MISMATCH = 34,
	HQ_RETURN_FORCE_DWORD = 0xffffffff
} _HQReturnVal;


#define HQFailed(r) (r!=HQ_OK)

#endif
